from django.urls import path
from .views import (
    ProductListCreateView,
    DashboardStatsView,
    ProductDetailView,
    NotificationsView,
    AnalyticsView,
    AIInsightsView,
    ProductSearchView,
    ProductSuggestView,
    upload_invoice,
    CreateOrderView,
    RetailerOrdersView,
    UpdateOrderStatusView,
    CreateSupplierOrderView,
    ListSupplierOrdersView,
    UpdateSupplierOrderStatusView,
    DistributorListView,
    DistributorCatalogView
)

urlpatterns = [
    path("products/", ProductListCreateView.as_view()),
    path("dashboard/", DashboardStatsView.as_view()),
    path("products/<int:product_id>/", ProductDetailView.as_view()),
    path("notifications/", NotificationsView.as_view()),
    path("analytics/", AnalyticsView.as_view()),
    path("ai-insights/", AIInsightsView.as_view()),
    path("search/", ProductSearchView.as_view()),
    path("suggest/", ProductSuggestView.as_view()),
    path("upload-invoice/", upload_invoice, name="upload_invoice"),
    path("orders/create/", CreateOrderView.as_view()),
    path("orders/retailer/", RetailerOrdersView.as_view()),
    path("orders/retailer/<int:order_id>/status/", UpdateOrderStatusView.as_view()),
    path("supplier-orders/create/", CreateSupplierOrderView.as_view()),
    path("supplier-orders/", ListSupplierOrdersView.as_view()),
    path("supplier-orders/<int:order_id>/status/", UpdateSupplierOrderStatusView.as_view()),
    path("distributors/", DistributorListView.as_view()),
    path("distributors/catalog/", DistributorCatalogView.as_view()),
]